version: '3'
services:
  nodejs_server:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: base_image
    container_name: nodejs_server
    volumes:
        - ./:/srv
    working_dir: /srv
    command: 'nodemon src/index.js'
    tty: true
    ports:
      - "3000:3000"